;;; flymake-hlint-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from flymake-hlint.el

(autoload 'flymake-hlint-load "flymake-hlint" "\
Configure flymake mode to check the current buffer's hlint syntax." t)
(register-definition-prefixes "flymake-hlint" '("flymake-hlint-"))

;;; End of scraped data

(provide 'flymake-hlint-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-hlint-autoloads.el ends here
