;;; slim-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from slim-mode.el

(autoload 'slim-mode "slim-mode" "\
Major mode for editing Slim files.

\\{slim-mode-map}

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.slim\\'" . slim-mode))
(register-definition-prefixes "slim-mode" '("html-tags" "slim-"))

;;; End of scraped data

(provide 'slim-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; slim-mode-autoloads.el ends here
