;;; reveal-in-osx-finder-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from reveal-in-osx-finder.el

(autoload 'reveal-in-osx-finder "reveal-in-osx-finder" "\
Reveal the file associated with the current buffer in the OS X Finder.
In a dired buffer, it will open the current directory." t)
(register-definition-prefixes "reveal-in-osx-finder" '("reveal-in-osx-finder-as"))

;;; End of scraped data

(provide 'reveal-in-osx-finder-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; reveal-in-osx-finder-autoloads.el ends here
